/*
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, 
find the sum of the even-valued terms.

FUNC takes number
    define a number
    FOR length of number
        number + i
        return number
    ENDFOR
ENDFUNC

*/
let a = 0
let b = 1
let thing = 0

function fibonacci(num) {
    let a = b
    let b = a + b

    for(i=0; i > num; i+a+b){
         
    }
    
}

console.log(fibonacci(100))